- hosts: localhost
  connection: local
  tasks:
    - name: get k8s_username
      shell: "oc whoami"
      register: username

    - name: get k8s_api_key
      shell: "oc whoami -t"
      register: token

    - set_fact:
        k8s_username={{username.stdout}}

    - set_fact:
        k8s_api_key={{token.stdout}}
